/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaccinuriRouteImport } from './routes/vaccinuri'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProgramulZileiRouteImport } from './routes/programul-zilei'
import { Route as PacientiRouteImport } from './routes/pacienti'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComunicareRouteImport } from './routes/comunicare'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CabinetSlugProgramariRouteImport } from './routes/cabinet.$slug.programari'
import { Route as ApiPublicConfirmAppointmentRouteImport } from './routes/api/public/confirm-appointment'

const VaccinuriRoute = VaccinuriRouteImport.update({
  id: '/vaccinuri',
  path: '/vaccinuri',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramulZileiRoute = ProgramulZileiRouteImport.update({
  id: '/programul-zilei',
  path: '/programul-zilei',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientiRoute = PacientiRouteImport.update({
  id: '/pacienti',
  path: '/pacienti',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicareRoute = ComunicareRouteImport.update({
  id: '/comunicare',
  path: '/comunicare',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetSlugProgramariRoute = CabinetSlugProgramariRouteImport.update({
  id: '/cabinet/$slug/programari',
  path: '/cabinet/$slug/programari',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfirmAppointmentRoute =
  ApiPublicConfirmAppointmentRouteImport.update({
    id: '/api/public/confirm-appointment',
    path: '/api/public/confirm-appointment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/comunicare': typeof ComunicareRoute
  '/login': typeof LoginRoute
  '/pacienti': typeof PacientiRoute
  '/programul-zilei': typeof ProgramulZileiRoute
  '/signup': typeof SignupRoute
  '/vaccinuri': typeof VaccinuriRoute
  '/api/public/confirm-appointment': typeof ApiPublicConfirmAppointmentRoute
  '/cabinet/$slug/programari': typeof CabinetSlugProgramariRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/comunicare': typeof ComunicareRoute
  '/login': typeof LoginRoute
  '/pacienti': typeof PacientiRoute
  '/programul-zilei': typeof ProgramulZileiRoute
  '/signup': typeof SignupRoute
  '/vaccinuri': typeof VaccinuriRoute
  '/api/public/confirm-appointment': typeof ApiPublicConfirmAppointmentRoute
  '/cabinet/$slug/programari': typeof CabinetSlugProgramariRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/comunicare': typeof ComunicareRoute
  '/login': typeof LoginRoute
  '/pacienti': typeof PacientiRoute
  '/programul-zilei': typeof ProgramulZileiRoute
  '/signup': typeof SignupRoute
  '/vaccinuri': typeof VaccinuriRoute
  '/api/public/confirm-appointment': typeof ApiPublicConfirmAppointmentRoute
  '/cabinet/$slug/programari': typeof CabinetSlugProgramariRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/comunicare'
    | '/login'
    | '/pacienti'
    | '/programul-zilei'
    | '/signup'
    | '/vaccinuri'
    | '/api/public/confirm-appointment'
    | '/cabinet/$slug/programari'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/comunicare'
    | '/login'
    | '/pacienti'
    | '/programul-zilei'
    | '/signup'
    | '/vaccinuri'
    | '/api/public/confirm-appointment'
    | '/cabinet/$slug/programari'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/comunicare'
    | '/login'
    | '/pacienti'
    | '/programul-zilei'
    | '/signup'
    | '/vaccinuri'
    | '/api/public/confirm-appointment'
    | '/cabinet/$slug/programari'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ComunicareRoute: typeof ComunicareRoute
  LoginRoute: typeof LoginRoute
  PacientiRoute: typeof PacientiRoute
  ProgramulZileiRoute: typeof ProgramulZileiRoute
  SignupRoute: typeof SignupRoute
  VaccinuriRoute: typeof VaccinuriRoute
  ApiPublicConfirmAppointmentRoute: typeof ApiPublicConfirmAppointmentRoute
  CabinetSlugProgramariRoute: typeof CabinetSlugProgramariRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaccinuri': {
      id: '/vaccinuri'
      path: '/vaccinuri'
      fullPath: '/vaccinuri'
      preLoaderRoute: typeof VaccinuriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programul-zilei': {
      id: '/programul-zilei'
      path: '/programul-zilei'
      fullPath: '/programul-zilei'
      preLoaderRoute: typeof ProgramulZileiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacienti': {
      id: '/pacienti'
      path: '/pacienti'
      fullPath: '/pacienti'
      preLoaderRoute: typeof PacientiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicare': {
      id: '/comunicare'
      path: '/comunicare'
      fullPath: '/comunicare'
      preLoaderRoute: typeof ComunicareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/$slug/programari': {
      id: '/cabinet/$slug/programari'
      path: '/cabinet/$slug/programari'
      fullPath: '/cabinet/$slug/programari'
      preLoaderRoute: typeof CabinetSlugProgramariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/confirm-appointment': {
      id: '/api/public/confirm-appointment'
      path: '/api/public/confirm-appointment'
      fullPath: '/api/public/confirm-appointment'
      preLoaderRoute: typeof ApiPublicConfirmAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ComunicareRoute: ComunicareRoute,
  LoginRoute: LoginRoute,
  PacientiRoute: PacientiRoute,
  ProgramulZileiRoute: ProgramulZileiRoute,
  SignupRoute: SignupRoute,
  VaccinuriRoute: VaccinuriRoute,
  ApiPublicConfirmAppointmentRoute: ApiPublicConfirmAppointmentRoute,
  CabinetSlugProgramariRoute: CabinetSlugProgramariRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
